pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yeswanthteja/java-microservice"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'develop', url: 'https://github.com/Yeswanthteja1010/java-microservice.git'
            }
        }

        stage('Build with Maven') {
            steps {
                echo 'mvn clean install'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('java-microservice') {
                    sh 'docker build -t yeswanthteja/java-microservice .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'Teja@1010', variable: 'DOCKERHUB_PASS')]) {
                    sh "echo $DOCKERHUB_PASS | docker login -u yeswanthteja --password-stdin"
                    sh "docker push $DOCKER_IMAGE"
                }
            }
        }

        stage('Run Container') {
            steps {
                sh "docker run -d -p 9090:8080 $DOCKER_IMAGE"
            }
        }
    }
}
